name: Playwright Dev Tests

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  # This token can be found in Curated Tests > vercel-storage-next-integration-test-suite > storage > vcs-integration-test-suite
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  # This token can be found in Curated Tests > vercel-storage-next-integration-test-suite > storage > vcs-integration-test-suite
  POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
  # This token can be found in Curated Tests > vercel-storage-next-integration-test-suite > storage > vcs-integration-test-suite-blob
  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
  # This token can be found in Curated Tests > vercel-storage-next-integration-test-suite > storage > vcs-integration-test-suite-kv
  KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
  # This token can be found in Curated Tests > vercel-storage-next-integration-test-suite > storage > vcs-integration-test-suite-kv
  KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # from https://dev.to/jpoehnelt/caching-playwright-binaries-in-github-actions-2mfc
      - uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - run: pnpm dlx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: pnpm dlx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'

      - name: Run Playwright tests in development mode
        run: pnpm integration-test
